// fast ticking clock
FAST_TICKING_CLOCK:
	ADD R[1] 1
	CMP R[1] 59
	GOTO FAST_TICKING_CLOCK
	LD R[1] 0 // reset minute to 0
	ADD R[0] 1
	CMP R[0] 23
	GOTO FAST_TICKING_CLOCK
	LD R[0] 0 // reset hour to 0
	GOTO FAST_TICKING_CLOCK
	EXIT