GOTO GAME_LOOP_1

// GAME_LOOP_1:
//     INPUT
//     MOVE MARIO
//     PLACE MARIO ARRAY IN VRAM
//     CLEAR SCREEN
//     BLIT
//     GOTO LOOP
// EXIT

GAME_LOOP_1:
    INPUT
    MOVE MARIO
    PLACE MARIO ARRAY IN VRAM
    CLEAR SCREEN
    BLIT
    GOTO LOOP
EXIT